//
//  Country.swift
//  TalkToMe
//
//  Created by Vlad on 1/8/24.
//

import SwiftUI

struct Country: Identifiable {
    var id: String { isoCode }
    let name: String
    let isoCode: String
    let phoneCode: String
    
    var flag: String {
        let base: UInt32 = 127397
        var s = ""
        for v in isoCode.uppercased().unicodeScalars {
            s.unicodeScalars.append(UnicodeScalar(base + v.value)!)
        }
        return String(s)
    }
    
    static let allCountries: [Country] = [
        // A
        Country(name: "Afghanistan", isoCode: "AF", phoneCode: "+93"),
        Country(name: "Albania", isoCode: "AL", phoneCode: "+355"),
        Country(name: "Algeria", isoCode: "DZ", phoneCode: "+213"),
        Country(name: "American Samoa", isoCode: "AS", phoneCode: "+1684"),
        Country(name: "Andorra", isoCode: "AD", phoneCode: "+376"),
        Country(name: "Angola", isoCode: "AO", phoneCode: "+244"),
        Country(name: "Anguilla", isoCode: "AI", phoneCode: "+1264"),
        Country(name: "Antarctica", isoCode: "AQ", phoneCode: "+672"),
        Country(name: "Antigua and Barbuda", isoCode: "AG", phoneCode: "+1268"),
        Country(name: "Argentina", isoCode: "AR", phoneCode: "+54"),
        Country(name: "Armenia", isoCode: "AM", phoneCode: "+374"),
        Country(name: "Aruba", isoCode: "AW", phoneCode: "+297"),
        Country(name: "Australia", isoCode: "AU", phoneCode: "+61"),
        Country(name: "Austria", isoCode: "AT", phoneCode: "+43"),
        Country(name: "Azerbaijan", isoCode: "AZ", phoneCode: "+994"),
        // B
        Country(name: "Bahamas", isoCode: "BS", phoneCode: "+1242"),
        Country(name: "Bahrain", isoCode: "BH", phoneCode: "+973"),
        Country(name: "Bangladesh", isoCode: "BD", phoneCode: "+880"),
        Country(name: "Barbados", isoCode: "BB", phoneCode: "+1246"),
        Country(name: "Belarus", isoCode: "BY", phoneCode: "+375"),
        Country(name: "Belgium", isoCode: "BE", phoneCode: "+32"),
        Country(name: "Belize", isoCode: "BZ", phoneCode: "+501"),
        Country(name: "Benin", isoCode: "BJ", phoneCode: "+229"),
        Country(name: "Bermuda", isoCode: "BM", phoneCode: "+1441"),
        Country(name: "Bhutan", isoCode: "BT", phoneCode: "+975"),
        Country(name: "Bolivia", isoCode: "BO", phoneCode: "+591"),
        Country(name: "Bosnia and Herzegovina", isoCode: "BA", phoneCode: "+387"),
        Country(name: "Botswana", isoCode: "BW", phoneCode: "+267"),
        Country(name: "Brazil", isoCode: "BR", phoneCode: "+55"),
        Country(name: "British Indian Ocean Territory", isoCode: "IO", phoneCode: "+246"),
        Country(name: "British Virgin Islands", isoCode: "VG", phoneCode: "+1284"),
        Country(name: "Brunei", isoCode: "BN", phoneCode: "+673"),
        Country(name: "Bulgaria", isoCode: "BG", phoneCode: "+359"),
        Country(name: "Burkina Faso", isoCode: "BF", phoneCode: "+226"),
        Country(name: "Burundi", isoCode: "BI", phoneCode: "+257"),
        // C
        Country(name: "Cambodia", isoCode: "KH", phoneCode: "+855"),
        Country(name: "Cameroon", isoCode: "CM", phoneCode: "+237"),
        Country(name: "Canada", isoCode: "CA", phoneCode: "+1"),
        Country(name: "Cape Verde", isoCode: "CV", phoneCode: "+238"),
        Country(name: "Cayman Islands", isoCode: "KY", phoneCode: "+1345"),
        Country(name: "Central African Republic", isoCode: "CF", phoneCode: "+236"),
        Country(name: "Chad", isoCode: "TD", phoneCode: "+235"),
        Country(name: "Chile", isoCode: "CL", phoneCode: "+56"),
        Country(name: "China", isoCode: "CN", phoneCode: "+86"),
        Country(name: "Christmas Island", isoCode: "CX", phoneCode: "+61"),
        Country(name: "Cocos (Keeling) Islands", isoCode: "CC", phoneCode: "+61"),
        Country(name: "Colombia", isoCode: "CO", phoneCode: "+57"),
        Country(name: "Comoros", isoCode: "KM", phoneCode: "+269"),
        Country(name: "Congo", isoCode: "CG", phoneCode: "+242"),
        Country(name: "Congo (Democratic Republic)", isoCode: "CD", phoneCode: "+243"),
        Country(name: "Cook Islands", isoCode: "CK", phoneCode: "+682"),
        Country(name: "Costa Rica", isoCode: "CR", phoneCode: "+506"),
        Country(name: "Croatia", isoCode: "HR", phoneCode: "+385"),
        Country(name: "Cuba", isoCode: "CU", phoneCode: "+53"),
        Country(name: "Curacao", isoCode: "CW", phoneCode: "+599"),
        Country(name: "Cyprus", isoCode: "CY", phoneCode: "+357"),
        Country(name: "Czech Republic", isoCode: "CZ", phoneCode: "+420"),
        // D
        Country(name: "Denmark", isoCode: "DK", phoneCode: "+45"),
        Country(name: "Djibouti", isoCode: "DJ", phoneCode: "+253"),
        Country(name: "Dominica", isoCode: "DM", phoneCode: "+1767"),
        Country(name: "Dominican Republic", isoCode: "DO", phoneCode: "+1"),
        // E
        Country(name: "East Timor", isoCode: "TL", phoneCode: "+670"),
        Country(name: "Ecuador", isoCode: "EC", phoneCode: "+593"),
        Country(name: "Egypt", isoCode: "EG", phoneCode: "+20"),
        Country(name: "El Salvador", isoCode: "SV", phoneCode: "+503"),
        Country(name: "Equatorial Guinea", isoCode: "GQ", phoneCode: "+240"),
        Country(name: "Eritrea", isoCode: "ER", phoneCode: "+291"),
        Country(name: "Estonia", isoCode: "EE", phoneCode: "+372"),
        Country(name: "Eswatini", isoCode: "SZ", phoneCode: "+268"),
        Country(name: "Ethiopia", isoCode: "ET", phoneCode: "+251"),
        // F
        Country(name: "Falkland Islands", isoCode: "FK", phoneCode: "+500"),
        Country(name: "Faroe Islands", isoCode: "FO", phoneCode: "+298"),
        Country(name: "Fiji", isoCode: "FJ", phoneCode: "+679"),
        Country(name: "Finland", isoCode: "FI", phoneCode: "+358"),
        Country(name: "France", isoCode: "FR", phoneCode: "+33"),
        Country(name: "French Guiana", isoCode: "GF", phoneCode: "+594"),
        Country(name: "French Polynesia", isoCode: "PF", phoneCode: "+689"),
        Country(name: "French Southern Territories", isoCode: "TF", phoneCode: "+262"),
        // G
        Country(name: "Gabon", isoCode: "GA", phoneCode: "+241"),
        Country(name: "Gambia", isoCode: "GM", phoneCode: "+220"),
        Country(name: "Georgia", isoCode: "GE", phoneCode: "+995"),
        Country(name: "Germany", isoCode: "DE", phoneCode: "+49"),
        Country(name: "Ghana", isoCode: "GH", phoneCode: "+233"),
        Country(name: "Gibraltar", isoCode: "GI", phoneCode: "+350"),
        Country(name: "Greece", isoCode: "GR", phoneCode: "+30"),
        Country(name: "Greenland", isoCode: "GL", phoneCode: "+299"),
        Country(name: "Grenada", isoCode: "GD", phoneCode: "+1473"),
        Country(name: "Guadeloupe", isoCode: "GP", phoneCode: "+590"),
        Country(name: "Guam", isoCode: "GU", phoneCode: "+1671"),
        Country(name: "Guatemala", isoCode: "GT", phoneCode: "+502"),
        Country(name: "Guinea", isoCode: "GN", phoneCode: "+224"),
        Country(name: "Guinea-Bissau", isoCode: "GW", phoneCode: "+245"),
        Country(name: "Guyana", isoCode: "GY", phoneCode: "+592"),
        // H
        Country(name: "Haiti", isoCode: "HT", phoneCode: "+509"),
        Country(name: "Honduras", isoCode: "HN", phoneCode: "+504"),
        Country(name: "Hong Kong", isoCode: "HK", phoneCode: "+852"),
        Country(name: "Hungary", isoCode: "HU", phoneCode: "+36"),
        // I
        Country(name: "Iceland", isoCode: "IS", phoneCode: "+354"),
        Country(name: "India", isoCode: "IN", phoneCode: "+91"),
        Country(name: "Indonesia", isoCode: "ID", phoneCode: "+62"),
        Country(name: "Iran", isoCode: "IR", phoneCode: "+98"),
        Country(name: "Iraq", isoCode: "IQ", phoneCode: "+964"),
        Country(name: "Ireland", isoCode: "IE", phoneCode: "+353"),
        Country(name: "Israel", isoCode: "IL", phoneCode: "+972"),
        Country(name: "Italy", isoCode: "IT", phoneCode: "+39"),
        Country(name: "Ivory Coast", isoCode: "CI", phoneCode: "+225"),
        // J
        Country(name: "Jamaica", isoCode: "JM", phoneCode: "+1876"),
        Country(name: "Japan", isoCode: "JP", phoneCode: "+81"),
        Country(name: "Jordan", isoCode: "JO", phoneCode: "+962"),
        // K
        Country(name: "Kazakhstan", isoCode: "KZ", phoneCode: "+7"),
        Country(name: "Kenya", isoCode: "KE", phoneCode: "+254"),
        Country(name: "Kiribati", isoCode: "KI", phoneCode: "+686"),
        Country(name: "Kuwait", isoCode: "KW", phoneCode: "+965"),
        Country(name: "Kyrgyzstan", isoCode: "KG", phoneCode: "+996"),
        // L
        Country(name: "Laos", isoCode: "LA", phoneCode: "+856"),
        Country(name: "Latvia", isoCode: "LV", phoneCode: "+371"),
        Country(name: "Lebanon", isoCode: "LB", phoneCode: "+961"),
        Country(name: "Lesotho", isoCode: "LS", phoneCode: "+266"),
        Country(name: "Liberia", isoCode: "LR", phoneCode: "+231"),
        Country(name: "Libya", isoCode: "LY", phoneCode: "+218"),
        Country(name: "Liechtenstein", isoCode: "LI", phoneCode: "+423"),
        Country(name: "Lithuania", isoCode: "LT", phoneCode: "+370"),
        Country(name: "Luxembourg", isoCode: "LU", phoneCode: "+352"),
        // M
        Country(name: "Madagascar", isoCode: "MG", phoneCode: "+261"),
        Country(name: "Malawi", isoCode: "MW", phoneCode: "+265"),
        Country(name: "Malaysia", isoCode: "MY", phoneCode: "+60"),
        Country(name: "Maldives", isoCode: "MV", phoneCode: "+960"),
        Country(name: "Mali", isoCode: "ML", phoneCode: "+223"),
        Country(name: "Malta", isoCode: "MT", phoneCode: "+356"),
        Country(name: "Marshall Islands", isoCode: "MH", phoneCode: "+692"),
        Country(name: "Martinique", isoCode: "MQ", phoneCode: "+596"),
        Country(name: "Mauritania", isoCode: "MR", phoneCode: "+222"),
        Country(name: "Mauritius", isoCode: "MU", phoneCode: "+230"),
        Country(name: "Mayotte", isoCode: "YT", phoneCode: "+262"),
        Country(name: "Mexico", isoCode: "MX", phoneCode: "+52"),
        Country(name: "Micronesia", isoCode: "FM", phoneCode: "+691"),
        Country(name: "Moldova", isoCode: "MD", phoneCode: "+373"),
        Country(name: "Monaco", isoCode: "MC", phoneCode: "+377"),
        Country(name: "Mongolia", isoCode: "MN", phoneCode: "+976"),
        Country(name: "Montenegro", isoCode: "ME", phoneCode: "+382"),
        Country(name: "Montserrat", isoCode: "MS", phoneCode: "+1664"),
        Country(name: "Morocco", isoCode: "MA", phoneCode: "+212"),
        Country(name: "Mozambique", isoCode: "MZ", phoneCode: "+258"),
        Country(name: "Myanmar", isoCode: "MM", phoneCode: "+95"),
        // N
        Country(name: "Namibia", isoCode: "NA", phoneCode: "+264"),
        Country(name: "Nauru", isoCode: "NR", phoneCode: "+674"),
        Country(name: "Nepal", isoCode: "NP", phoneCode: "+977"),
        Country(name: "Netherlands", isoCode: "NL", phoneCode: "+31"),
        Country(name: "New Caledonia", isoCode: "NC", phoneCode: "+687"),
        Country(name: "New Zealand", isoCode: "NZ", phoneCode: "+64"),
        Country(name: "Nicaragua", isoCode: "NI", phoneCode: "+505"),
        Country(name: "Niger", isoCode: "NE", phoneCode: "+227"),
        Country(name: "Nigeria", isoCode: "NG", phoneCode: "+234"),
        Country(name: "Niue", isoCode: "NU", phoneCode: "+683"),
        Country(name: "Norfolk Island", isoCode: "NF", phoneCode: "+672"),
        Country(name: "North Korea", isoCode: "KP", phoneCode: "+850"),
        Country(name: "North Macedonia", isoCode: "MK", phoneCode: "+389"),
        Country(name: "Northern Mariana Islands", isoCode: "MP", phoneCode: "+1670"),
        Country(name: "Norway", isoCode: "NO", phoneCode: "+47"),
        // O
        Country(name: "Oman", isoCode: "OM", phoneCode: "+968"),
        // P
        Country(name: "Pakistan", isoCode: "PK", phoneCode: "+92"),
        Country(name: "Palau", isoCode: "PW", phoneCode: "+680"),
        Country(name: "Palestine", isoCode: "PS", phoneCode: "+970"),
        Country(name: "Panama", isoCode: "PA", phoneCode: "+507"),
        Country(name: "Papua New Guinea", isoCode: "PG", phoneCode: "+675"),
        Country(name: "Paraguay", isoCode: "PY", phoneCode: "+595"),
        Country(name: "Peru", isoCode: "PE", phoneCode: "+51"),
        Country(name: "Philippines", isoCode: "PH", phoneCode: "+63"),
        Country(name: "Pitcairn Islands", isoCode: "PN", phoneCode: "+64"),
        Country(name: "Poland", isoCode: "PL", phoneCode: "+48"),
        Country(name: "Portugal", isoCode: "PT", phoneCode: "+351"),
        Country(name: "Puerto Rico", isoCode: "PR", phoneCode: "+1"),
        // Q
        Country(name: "Qatar", isoCode: "QA", phoneCode: "+974"),
        // R
        Country(name: "Republic of the Congo", isoCode: "CG", phoneCode: "+242"),
        Country(name: "Romania", isoCode: "RO", phoneCode: "+40"),
        Country(name: "Russia", isoCode: "RU", phoneCode: "+7"),
        Country(name: "Rwanda", isoCode: "RW", phoneCode: "+250"),
        // S
        Country(name: "Saint Kitts and Nevis", isoCode: "KN", phoneCode: "+1869"),
        Country(name: "Saint Lucia", isoCode: "LC", phoneCode: "+1758"),
        Country(name: "Saint Vincent and the Grenadines", isoCode: "VC", phoneCode: "+1784"),
        Country(name: "Samoa", isoCode: "WS", phoneCode: "+685"),
        Country(name: "San Marino", isoCode: "SM", phoneCode: "+378"),
        Country(name: "Sao Tome and Principe", isoCode: "ST", phoneCode: "+239"),
        Country(name: "Saudi Arabia", isoCode: "SA", phoneCode: "+966"),
        Country(name: "Senegal", isoCode: "SN", phoneCode: "+221"),
        Country(name: "Serbia", isoCode: "RS", phoneCode: "+381"),
        Country(name: "Seychelles", isoCode: "SC", phoneCode: "+248"),
        Country(name: "Sierra Leone", isoCode: "SL", phoneCode: "+232"),
        Country(name: "Singapore", isoCode: "SG", phoneCode: "+65"),
        Country(name: "Sint Maarten", isoCode: "SX", phoneCode: "+1721"),
        Country(name: "Slovakia", isoCode: "SK", phoneCode: "+421"),
        Country(name: "Slovenia", isoCode: "SI", phoneCode: "+386"),
        Country(name: "Solomon Islands", isoCode: "SB", phoneCode: "+677"),
        Country(name: "Somalia", isoCode: "SO", phoneCode: "+252"),
        Country(name: "South Africa", isoCode: "ZA", phoneCode: "+27"),
        Country(name: "South Korea", isoCode: "KR", phoneCode: "+82"),
        Country(name: "South Sudan", isoCode: "SS", phoneCode: "+211"),
        Country(name: "Spain", isoCode: "ES", phoneCode: "+34"),
        Country(name: "Sri Lanka", isoCode: "LK", phoneCode: "+94"),
        Country(name: "Sudan", isoCode: "SD", phoneCode: "+249"),
        Country(name: "Suriname", isoCode: "SR", phoneCode: "+597"),
        Country(name: "Swaziland", isoCode: "SZ", phoneCode: "+268"),
        Country(name: "Sweden", isoCode: "SE", phoneCode: "+46"),
        Country(name: "Switzerland", isoCode: "CH", phoneCode: "+41"),
        Country(name: "Syria", isoCode: "SY", phoneCode: "+963"),
        // T
        Country(name: "Taiwan", isoCode: "TW", phoneCode: "+886"),
        Country(name: "Tajikistan", isoCode: "TJ", phoneCode: "+992"),
        Country(name: "Tanzania", isoCode: "TZ", phoneCode: "+255"),
        Country(name: "Thailand", isoCode: "TH", phoneCode: "+66"),
        Country(name: "Togo", isoCode: "TG", phoneCode: "+228"),
        Country(name: "Tonga", isoCode: "TO", phoneCode: "+676"),
        Country(name: "Trinidad and Tobago", isoCode: "TT", phoneCode: "+1868"),
        Country(name: "Tunisia", isoCode: "TN", phoneCode: "+216"),
        Country(name: "Turkey", isoCode: "TR", phoneCode: "+90"),
        Country(name: "Turkmenistan", isoCode: "TM", phoneCode: "+993"),
        Country(name: "Tuvalu", isoCode: "TV", phoneCode: "+688"),
        // U
        Country(name: "Uganda", isoCode: "UG", phoneCode: "+256"),
        Country(name: "Ukraine", isoCode: "UA", phoneCode: "+380"),
        Country(name: "United Arab Emirates", isoCode: "AE", phoneCode: "+971"),
        Country(name: "United Kingdom", isoCode: "GB", phoneCode: "+44"),
        Country(name: "United States", isoCode: "US", phoneCode: "+1"),
        Country(name: "Uruguay", isoCode: "UY", phoneCode: "+598"),
        Country(name: "Uzbekistan", isoCode: "UZ", phoneCode: "+998"),
        // V
        Country(name: "Vanuatu", isoCode: "VU", phoneCode: "+678"),
        Country(name: "Vatican City", isoCode: "VA", phoneCode: "+379"),
        Country(name: "Venezuela", isoCode: "VE", phoneCode: "+58"),
        Country(name: "Vietnam", isoCode: "VN", phoneCode: "+84"),
        // W
        Country(name: "Western Sahara", isoCode: "EH", phoneCode: "+212"),
        // X --
        // Y
        Country(name: "Yemen", isoCode: "YE", phoneCode: "+967"),
        // Z
        Country(name: "Zambia", isoCode: "ZM", phoneCode: "+260"),
        Country(name: "Zimbabwe", isoCode: "ZW", phoneCode: "+263")
    ]
}
